version: 2
sphinx:
  configuration: docs/conf.py
formats:
  - pdf
build:
  os: ubuntu-24.04
  commands:
    # setup uv
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    # setup tox + tox-uv
    - uv tool install tox --with tox-uv --python "3.14" --managed-python
    # setup the docs tox environment, but use `--notest` to skip commands
    - uv tool run tox run -e docs --notest -vvv
    # do the actual build step, to the RTD documented output directory
    - uv tool run tox run -e docs --skip-pkg-install -q -- "${READTHEDOCS_OUTPUT}"/html -b dirhtml
