[project]
name = "webargs"
version = "8.7.1"
description = "Declarative parsing and validation of HTTP request objects, with built-in support for popular web frameworks, including Flask, Django, Bottle, Tornado, Pyramid, Falcon, and aiohttp."
readme = "README.rst"
license = "MIT"
authors = [{ name = "Steven Loria", email = "oss@stevenloria.com" }]
maintainers = [
  { name = "Steven Loria", email = "oss@stevenloria.com" },
  { name = "Jérôme Lafréchoux", email = "jerome@jolimont.fr" },
  { name = "Stephen Rosen", email = "sirosen0@gmail.com" },
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
keywords = [
  "webargs",
  "http",
  "flask",
  "django",
  "bottle",
  "tornado",
  "aiohttp",
  "request",
  "arguments",
  "validation",
  "parameters",
  "rest",
  "api",
  "marshmallow",
]
requires-python = ">=3.10"
dependencies = [
  "marshmallow>=4.0.0,<5.0.0",
  "packaging>=17.0",
  # depend on typing-extensions conditionally for annotations
  'typing_extensions>=4.0; python_version<"3.10"',
]

[project.urls]
Changelog = "https://webargs.readthedocs.io/en/latest/changelog.html"
Funding = "https://opencollective.com/marshmallow"
Issues = "https://github.com/marshmallow-code/webargs/issues"
Source = "https://github.com/marshmallow-code/webargs"
Tidelift = "https://tidelift.com/subscription/pkg/pypi-webargs?utm_source=pypi-webargs&utm_medium=pypi"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[dependency-groups]
docs = ["Sphinx", "sphinx-issues", "furo"]
tests = [
  "pytest",
  "pytest-asyncio",
  "webtest==3.0.7",
  "webtest-aiohttp==2.0.0",
  "pytest-aiohttp>=0.3.0",
  "packaging>=17.0",
]
test-flask = ["Flask>=3.1.0", { include-group = "tests" }]
test-django = ["Django>=5.2.0", { include-group = "tests" }]
test-bottle = ["bottle>=0.13.0", { include-group = "tests" }]
test-tornado = ["tornado>=6.5.0", { include-group = "tests" }]
test-pyramid = [
  "pyramid>=2.0.2",
  { include-group = "tests" },
  # temporary pin: hold back `setuptools` so that `pyramid` testing works
  # pyramid uses pkg_resources, which has been long deprecated and finally removed
  #
  # see https://github.com/Pylons/pyramid/issues/3731 for discussion within pyramid
  "setuptools <82.1",
]
test-falcon = ["falcon>=4.1.0", { include-group = "tests" }]
test-aiohttp = ["aiohttp>=3.13.0", { include-group = "tests" }]
# for efficiency of testing, we define this group and test all frameworks at once, because it works
# however, each is declared separately in case we ever encounter conflicts and need to break one off
# from the rest of the group
test-all-frameworks = [
  { include-group = "test-flask" },
  { include-group = "test-django" },
  { include-group = "test-bottle" },
  { include-group = "test-tornado" },
  { include-group = "test-pyramid" },
  { include-group = "test-falcon" },
  { include-group = "test-aiohttp" },
]

dev = ["tox", "pre-commit>=3.5,<5.0", { include-group = "tests" }]

[tool.uv]
exclude-newer = "1 week"

[tool.flit.sdist]
include = [
  "docs/",
  "tests/",
  "CHANGELOG.rst",
  "CONTRIBUTING.rst",
  "SECURITY.md",
  "NOTICE",
  "tox.ini",
]
exclude = ["docs/_build/"]

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
ignore = ["E203", "E266", "E501", "E731"]
select = [
  "B",  # flake8-bugbear
  "E",  # pycodestyle error
  "F",  # pyflakes
  "I",  # isort
  "UP", # pyupgrade
  "W",  # pycodestyle warning
]

[tool.pytest.ini_options]
filterwarnings = [
  # https://github.com/Pylons/pyramid/issues/3731
  "ignore:.*pkg_resources.*:DeprecationWarning",
  # https://github.com/Pylons/webob/issues/437
  "ignore:.*'cgi' is deprecated.*:DeprecationWarning",
  # https://github.com/sloria/webtest-aiohttp/issues/6
  "ignore:.*The object should be created within an async function.*:DeprecationWarning",
]

[tool.mypy]
ignore_missing_imports = true
warn_unreachable = true
warn_unused_ignores = true
warn_redundant_casts = true
# warn_return_any = true
warn_no_return = true
no_implicit_optional = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
disallow_untyped_defs = false
module = [
  "webargs.fields",
  "webargs.testing",
  "webargs.aiohttpparser",
  "webargs.bottleparser",
  "webargs.djangoparser",
  "webargs.falconparser",
  "tests.*",
]
