[tox]
envlist=
    lint
    py{310,311,312,313,314}-marshmallow
    py314-marshmallowdev
    py310-lowest
    docs

[testenv]
dependency_groups = test-all-frameworks
deps =
    marshmallow: marshmallow>=4.0.0,<5.0.0
    marshmallowdev: https://github.com/marshmallow-code/marshmallow/archive/dev.tar.gz
    lowest: flask==3.1.0
    lowest: Django==5.2.0
    lowest: bottle==0.13.0
    lowest: tornado==6.5.0
    lowest: pyramid==2.0.2
    lowest: falcon==4.1.0
    lowest: aiohttp==3.13.0
    lowest: marshmallow==4.0.0
commands = pytest {posargs}

[testenv:lint]
deps = pre-commit~=4.0
skip_install = true
commands = pre-commit run --all-files

# a separate `mypy` target which runs `mypy` in an environment with
# `webargs` and `marshmallow` both installed is a valuable safeguard against
# issues in which `mypy` running on every file standalone won't catch things
[testenv:mypy]
deps = mypy==1.11.0
extras = frameworks
commands = mypy src/ {posargs}

[testenv:docs]
dependency_groups = docs
commands = sphinx-build docs/ {posargs:docs/_build}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
deps = sphinx-autobuild
dependency_groups = docs
commands = sphinx-autobuild --port=0 --open-browser --delay=2 docs/ docs/_build {posargs} --watch src --watch CONTRIBUTING.rst --watch README.rst

[testenv:readme-serve]
deps = restview
skip_install = true
commands = restview README.rst

