[tox]
requires = tox-uv
envlist=
    lint
    py{310,311,312,313,314}-marshmallow
    py314-marshmallowdev
    py310-lowest
    docs

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test-all-frameworks
commands = pytest {posargs}

[testenv:py314-marshmallowdev]
runner = uv-venv-runner
deps = https://github.com/marshmallow-code/marshmallow/archive/dev.tar.gz

[testenv:py310-lowest]
runner = uv-venv-runner
deps =
    flask==3.1.0
    Django==5.2.0
    bottle==0.13.0
    tornado==6.5.0
    pyramid==2.0.2
    falcon==4.1.0
    aiohttp==3.13.0
    marshmallow==4.0.0

[testenv:lint]
dependency_groups = lint
skip_install = true
commands = pre-commit run --all-files

# a separate `mypy` target which runs `mypy` in an environment with
# `webargs` and `marshmallow` both installed is a valuable safeguard against
# issues in which `mypy` running on every file standalone won't catch things
[testenv:mypy]
runner = uv-venv-runner
deps = mypy==1.11.0
extras = frameworks
commands = mypy src/ {posargs}

[testenv:docs]
dependency_groups = docs
commands = sphinx-build docs/ {posargs:docs/_build}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
runner = uv-venv-runner
deps = sphinx-autobuild
dependency_groups = docs
commands = sphinx-autobuild --port=0 --open-browser --delay=2 docs/ docs/_build {posargs} --watch src --watch README.rst

[testenv:readme-serve]
runner = uv-venv-runner
deps = restview
skip_install = true
commands = restview README.rst
